
version: "3"
 
services:
  db:
    image: postgres
    container_name: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: db_name
      POSTGRES_USER: postgres_n
      POSTGRES_PASSWORD: postgres_p
    ports:
      - 5432:5432

  redis:
      image: redis
      container_name: redis
      ports:
        - 6379:6379
      volumes:
        - ./data:/data
      restart: always
